version: '3.8'
services:
  db:
    image: postgres:15
    container_name: eventnexus_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: eventnexus
      TZ: Asia/Kolkata
    command: >
      sh -c "ln -snf /usr/share/zoneinfo/Asia/Kolkata /usr/share/zoneinfo/Asia/Calcutta && docker-entrypoint.sh postgres -c timezone=Asia/Kolkata"
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
